### ISSUE TITLE
Bug: Club cards fade in

### ISSUE THREAD

**Issue by tamalCodes** [ngoworldcommunity/NGOWorld#1211]
### Description

Currently, the cuts are looking very sharp We might need to add some hazy effect so that it looks like they are fading in gradually rather than total separable cuts- this can be done with CSS.

Checkout the fade in a style that I have attached in one of the screenshot.

### Proposed Solution

Different styles can be implemented for a `fade away` effect.

### Screenshots

![image](https://github.com/milancommunity/Milan/assets/72851613/0d12e336-2e00-42cf-bebf-033985138293)

![image](https://github.com/milancommunity/Milan/assets/72851613/88da5ae5-9cff-4eac-831a-88afdc9e05ce)

### Browser 🥦

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/MilanCommunity/Milan/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/MilanCommunity/Milan/blob/main/CONTRIBUTING.md)
- [X] I am participating in JWOC
- [ ] I am participating in IWOC
- [ ] I am willing to work on this issue (blank for no).

**Comment by Anushkabh** [comment]
i would like to work under JWOC .. kindly assign @tamalCodes

**Comment by tamalCodes** [comment]
Yeah sure go ahead @Anushkabh

**Comment by r0ld3x** [comment]
https://github.com/milancommunity/Milan/assets/77254818/960609b5-7c42-442b-9ea8-66723ff33bdb

here i added 

```css
border-radius: 30px;
box-shadow: 
  inset -10px 0 10px -10px rgba(0, 0, 0, 0.5),
  inset 10px 0 10px -10px rgba(0, 0, 0, 0.5);
```

I dont know how to index that shadow to the top 
I tried different ways but still could not found any solution.

**Comment by tamalCodes** [comment]
These all might need fixes , do make a PR, I'll take a look at the code and run it locally
![image](https://github.com/milancommunity/Milan/assets/72851613/75024067-55d1-4c53-9245-f1fecf492d96)

**Comment by r0ld3x** [comment]
> These all might need fixes , do make a PR, I'll take a look at the code and run it locally
> ![image](https://github.com/milancommunity/Milan/assets/72851613/75024067-55d1-4c53-9245-f1fecf492d96)
> 

Ok
