### ISSUE TITLE
Feature: Updating profile picture functionality and UI

### ISSUE THREAD

**Issue by tamalCodes** [ngoworldcommunity/NGOWorld#1218]
### Description

Currently, there is no way to update the profile picture that is provided by default so updating it or having an option to do the same would be amazing 

since the back end is not yet ready for this the idea is to make sure the front-end flow is ready properly along with some changes to the UI for updating a picture. 

### Proposed Solution

- We already have a model popping up for editing our profile on our profile page
- We can do the same for the image or we can have the model open up but show the field only for the image that way it would be much more convenient
- The Redux store must also be updated so that it shows the latest data for the image as well

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/MilanCommunity/Milan/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/MilanCommunity/Milan/blob/main/CONTRIBUTING.md)
- [ ] I am participating in JWOC
- [ ] I am participating in IWOC
- [ ] I am willing to work on this issue (blank for no)

**Comment by gaganit1265** [comment]
@tamalCodes  Can you please add the existing pop up model

**Comment by tamalCodes** [comment]
There is no existing modal, we have a modal just for editing a profile
![image](https://github.com/milancommunity/Milan/assets/72851613/062b9518-6d17-4144-b070-fe008083240c)

However we do not have any option to update the user's profile picture, so we need to have that. IF you take a look at GitHub, you can go to your github's profile, click on edit, and then you have an edit icon for the profile picture.

![image](https://github.com/milancommunity/Milan/assets/72851613/37f87bd8-9e61-4852-8c9c-8ed3a3cb165d)

On clicking it we have multiple options, an edit button and a remove button which further does the needed action
![image](https://github.com/milancommunity/Milan/assets/72851613/f797896a-79e9-46ed-be16-363eb48b3c34)

So I was wondering if we could have something similar for the image in the profile's section

**Comment by ndmaratha** [comment]
we can use cloudinary for this it will convert the image into the link and then we just have to modify our backend litte much

**Comment by tamalCodes** [comment]
That can be done, but do i need to pay for it ?

**Comment by ndmaratha** [comment]
yes according to me cloudynary charge for this , But it is good to store our image as a string in database

**Comment by rutupatel53** [comment]
can you assign me this task @tamalCodes ?

**Comment by tamalCodes** [comment]
Sure , go ahead @rutupatel53 . Please react to this message so that I know you are working on the same !
