### ISSUE TITLE
Feature: Revamping Footer

### ISSUE THREAD

**Issue by tamalCodes** [ngoworldcommunity/NGOWorld#1219]
### Description

The current footer kind of looks out of place because the color theme is different inside of it and also it has a bunch of different fonts other than what we generally use across the whole website. We also maintain a very clear and minimal design across the whole product but in the case of the footer it is not the same there are multiple elements present in the footer which makes the user experience pretty much weird.,

### Proposed Solution

- One solution would be to revamp the footer maintaining the colour theme of the current website
- Remove a couple of elements from the footer such as the duplicate GitHub links social media links and also the Contact Us button
- Take inspiration from footers of other products and build something very similar and it also must be responsive

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/MilanCommunity/Milan/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/MilanCommunity/Milan/blob/main/CONTRIBUTING.md)
- [ ] I am participating in JWOC
- [ ] I am participating in IWOC
- [ ] I am willing to work on this issue (blank for no)

**Comment by motuncoded** [comment]
I would like to work on this issue

**Comment by tamalCodes** [comment]
Sure go ahead, please follow the docs to get a better idea of what NOT to do and HOW to do.

- [Local project setup, .env](https://github.com/MilanCommunity/Milan#1%EF%B8%8F-setting-up-the-project-locally) for the frontend.
- [Contributing guidelines](https://github.com/MilanCommunity/Milan#2%EF%B8%8F-contributing-guidelines--more) to be followed.


Please maintain structure, use conventional pull request titles, and avoid spam to avoid closure or bans.

**Comment by motuncoded** [comment]
Can you send a snap shot of a website I can you?

**Comment by tamalCodes** [comment]
What snapshot are you talking about ?

**Comment by motuncoded** [comment]
No, I am not. Kind of engaged right now

**Comment by ninjasun** [comment]
Hi @tamalCodes I would like to work on this issue

**Comment by tamalCodes** [comment]
That sounds great @ninjasun , please go ahead - this is a priority, and would like to get it done faster 🚀.
Please read our docs for help.

**Comment by ninjasun** [comment]
Thanks, @tamalCodes I got a few style changes following your instructions and theme colors. Could you clarify the PR for me? I cloned the beta repository and I'm going to push over there. What's the next step?
