### ISSUE TITLE
Feature: Use .env file for Port, Network Expose and remove React Scripts

### ISSUE THREAD

**Issue by developerTested** [ngoworldcommunity/NGOWorld#1230]
### Description

Currently package.json contain **React-Scripts** which is not being used in my view.

Vite development Port is set in **package.json** and **Vite.config.js** which is HardCoded so it should be **.env** file based so if repo update user changes regrading PORT and NETWORK expose shouldn't be override by updates.

### Proposed Solution

1. Remove port from package.json and vite config
2. Remove React-Scripts

### 🥦 Browser

Mozilla Firefox

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/MilanCommunity/Milan/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/MilanCommunity/Milan/blob/main/CONTRIBUTING.md)
- [ ] I am participating in JWOC
- [ ] I am participating in IWOC
- [X] I am willing to work on this issue (blank for no)

**Comment by r0ld3x** [comment]
I think vite --port 3000 solves this problem

**Comment by developerTested** [comment]
> I think vite --port 3000 solves this problem

You're but that is issue because that is hardcoded in p**ackage.json** which can be overridden when thee is an update in **package.json** so to bypass that u need to store it somewhere user have control over it. 

Check repo **package.json** and **vite.config.js** there its Hardcoded.

if we use .env file no user change will be overridden which is main aim of this issue

**Comment by tamalCodes** [comment]
Hey @developerTested , this is a good DX - please start working on the same.

Also yes, I guess we never removed the unused dependencies - while you are at it, do remove the unused ones. Add documentation and update `.env.example` for the same.

## 📑 Checklist in case you missed something

- [Local project setup, .env](https://github.com/MilanCommunity/Milan#1%EF%B8%8F-setting-up-the-project-locally) for the frontend.
- [Contributing guidelines](https://github.com/MilanCommunity/Milan#2%EF%B8%8F-contributing-guidelines--more) to be followed.


Please maintain structure, use conventional pull request titles, and avoid spam to avoid closure or bans.
