### ISSUE TITLE
Feature: Skeleton loading

### ISSUE THREAD

**Issue by tamalCodes** [ngoworldcommunity/NGOWorld#1236]
### Description

- Because of Internet connection constraints the data might load at a certain delayed amount for different users and we do not have any loading animation for the same
- As you can see from the screenshot section down below you will notice that for clubs the images take time to load as a result there is an almost empty screen for events because the whole events are compiled as one single section it takes some time to load too
- The point is we need to have some kind of loading states or loading transition or animation available globally such that it matches our theme and we reuse it everywhere

### Proposed Solution

![image](https://github.com/milancommunity/Milan/assets/72851613/4b9ada94-4131-45ff-9c8a-28622f74a8fe)

We also need a skeleton animation for example vercel has their skeleton animation you can take inspiration from these and maybe build something very similar to it

### Screenshots

![image](https://github.com/milancommunity/Milan/assets/72851613/734cd9e9-d745-4c11-800f-f7f8b051aea9)
![image](https://github.com/milancommunity/Milan/assets/72851613/699a8936-c493-479f-961d-5d3226faadb1)

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/MilanCommunity/Milan/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/MilanCommunity/Milan/blob/main/CONTRIBUTING.md)
- [ ] I am participating in JWOC
- [ ] I am participating in IWOC
- [ ] I am willing to work on this issue (blank for no)

**Comment by Piyush-linux** [comment]
Working on this one 💚

**Comment by tirthkparikh** [comment]
Hello Tama, would love to contribute let me know if i can work on it
