### ISSUE TITLE
Feature: Migration from Plain CSS to Tailwind CSS

### ISSUE THREAD

**Issue by Piyush-linux** [ngoworldcommunity/NGOWorld#1239]
### Description

As the project will grow more and more we should consider styling elements from the start.
- Plain CSS require single entity file
- It demands more line of code and naming convention

### Proposed Solution

**Tailwind CSS**
- To do a migration from CSS to tailwind step by step
- Styling could be done under that component it self
- Styling becomes more easy and less code maintenance
> if require we can discuss about migration before PR

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/MilanCommunity/Milan/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/MilanCommunity/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue

**Comment by Piyush-linux** [comment]
Yo @tamalCodes , Could I work on this One

**Comment by Sanyam2000-dot** [comment]
I want to work on this issue. Please assign it to me.

**Comment by Sanyam2000-dot** [comment]
#1251

**Comment by Sanyam2000-dot** [comment]
Please find the pr attached below #1251
