### ISSUE TITLE
Bug: Social Links in footer section not working

### ISSUE THREAD

**Issue by jinx-vi-0** [ngoworldcommunity/NGOWorld#1255]
### Description

Social Links (Twitter, LinkedIn, GitHub, Mail) in footer section not working

### Proposed Solution

Link all the social profiles

### Browser 🥦

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/ngoworldcommunity/NGOWorld/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ngoworldcommunity/NGOWorld/blob/main/CONTRIBUTING.md)
- [ ] I am participating in JWOC
- [ ] I am participating in IWOC
- [X] I am willing to work on this issue (blank for no).

**Comment by Nirpendra09** [comment]
Hi @tamalCodes Can you assign this to me>
