### ISSUE TITLE
Feature: Improve Card Clickability in Clubs Route

### ISSUE THREAD

**Issue by Kaarthik-07** [ngoworldcommunity/NGOWorld#1257]
### Description

In the current implementation of the clubs route, users must click on a specific icon within a card to be redirected to the corresponding page. This is not an intuitive user experience, as most users expect to be able to click anywhere on the card to navigate to the next page. This design can lead to frustration and confusion, as users may repeatedly click on the card without realizing they need to click the icon.

### Proposed Solution

Enhance the user experience by making the entire card clickable. This would involve adding a redirect functionality so that when a user clicks anywhere on the card, they are taken to the relevant page. This change would align with common user interface practices and make the navigation process smoother and more intuitive for users.

### 🥦 Browser

Other

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/ngoworldcommunity/NGOWorld/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ngoworldcommunity/NGOWorld/blob/main/CONTRIBUTING.md)
- [ ] I am participating in JWOC
- [ ] I am participating in IWOC
- [X] I am willing to work on this issue (blank for no)

**Comment by sanjheev100** [comment]
Hi @tamalCodes 

Can i take this up and work on it
