### ISSUE TITLE
Bug: Signup Button Loader Runs Without Email and Password Input

### ISSUE THREAD

**Issue by st17931** [ngoworldcommunity/NGOWorld#1258]
### Description

The loader on the Signup button is triggered even when there are no values entered in the email and password fields. This behavior is unexpected, as the loader should only activate when the user has entered valid data and submitted the form.

**Steps to Reproduce:**

1.     Navigate to the Signup page.
2.     Leave the email and password fields empty.
3.     Click on the Signup button.

**Expected Behavior:** The Signup button should only show the loader when valid inputs are provided and the form is submitted.

**Actual Behavior:** The loader is activated immediately upon clicking the Signup button, regardless of whether the email and password fields are filled.

**Impact:** This bug may confuse users as it suggests that the signup process has started when it has not.

### Proposed Solution

To resolve this issue, we will implement the following changes:

**Remove Loader on Empty Fields:**
We will modify the logic to ensure that the loader does not run when the email and password fields are empty. This will prevent unnecessary loading indicators when the form is incomplete.

**Trigger Loader on Valid Input:**
The loader will be activated only when both the email and password fields have valid input and the user submits the form. This ensures that the loading state reflects the actual processing of the signup request.

**Form Validation:**
Before triggering the loader, the form will be validated to check if the required fields (email and password) are filled. If validation passes, the loader will be triggered; otherwise, an appropriate error message will be displayed without initiating the loader.

### Screenshots

[Signup_page_issue.webm](https://github.com/user-attachments/assets/acf66515-edfd-4c10-a2fb-5b8409b13a84)
![Signup_loader_issue](https://github.com/user-attachments/assets/5f813e01-5a46-449e-9eb1-d9a97d6df48a)

### Browser 🥦

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/ngoworldcommunity/NGOWorld/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ngoworldcommunity/NGOWorld/blob/main/CONTRIBUTING.md)
- [ ] I am participating in JWOC
- [ ] I am participating in IWOC
- [X] I am willing to work on this issue (blank for no).

**Comment by Nirpendra09** [comment]
Hi @tamalCodes can you assign this to me?

**Comment by shreya-mangade** [comment]
Hello @tamalCodes ,
Can you please assign this issue to me?

**Comment by r0ld3x** [comment]
@tamalCodes hey can you assign me?
